### ISSUE TITLE
Error when running pytest

### ISSUE THREAD

**Issue by alexfoias** [shimming-toolbox/shimming-toolbox#163] opened 2020-11-05 16:08 UTC
I cloned the repo.
I created & activated venv: `conda create -n shim_venv python=3.7`.
I installed the package: `pip install -e ".[docs]"`
When running `pytest` I get errors. See log [here](https://gist.github.com/alexfoias/52a356301b168f47abfc6e7ea5fd78ea).

**Comment by gaspardcereza** [comment] 2020-11-05 16:14
It seems similar to #130 (with even more returned errors) for which we didn't really find a solution... If it passes on Travis, it doesn't pass locally and vice-versa...

**Comment by po09i** [comment] 2020-11-05 18:17
All errors except one seem to be due to prelude not being installed. The other error (load_nifti) is related to #130 as gaspard mentioned.

You can run pytest without prelude using `pytest -m "not prelude"` (It will not do the tests that require prelude)

**Comment by alexfoias** [comment] 2020-11-05 18:28
Yes, I don't have prelude installed. I can install it and rerun it.

**Comment by jcohenadad** [comment] 2020-11-05 18:37
for the record, the soft-dependency testing is documented [here](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html?highlight=pytest#testing-subsets-of-soft-dependencies)

**Comment by alexfoias** [comment] 2020-11-05 19:13
I ran it without the soft-dependecies [here](https://gist.github.com/alexfoias/4642e44cde25c4aebab8945b7bf8bc4e).

**Comment by jidicula** [comment] 2020-11-06 01:42
I just took a look at your build logs and also tried reproducing your steps – can confirm it's a duplicate of #130.

**Closed as completed by jidicula** 2020-11-06 01:42 UTC
Labels: bug
