### ISSUE TITLE
mention that this algorithm also encourages high B1+ efficiency

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#355] opened 2022-03-11 17:27 UTC
from https://github.com/shimming-toolbox/shimming-toolbox/pull/352

https://github.com/shimming-toolbox/shimming-toolbox/blob/98eea3168e18ea418960d9cf94d032c5a652c940/shimmingtoolbox/shim/b1shim.py#L24

**Comment by gaspardcereza** [comment] 2022-03-11 18:57
Duplicate of #356

**Closed as completed by gaspardcereza** 2022-03-11 18:57 UTC
