### ISSUE TITLE
st_prepare_fieldmap RuntimeError : read_nii must range from -pi to pi

### ISSUE THREAD

**Issue by KevinBerard** [shimming-toolbox/shimming-toolbox#293] opened 2021-07-22 16:02 UTC
### Checklist

- [X] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [X] I've described my environment
- [X] I've described the bug
- [X] I've described the steps to reproduce the behaviour
- [X] I've included screenshots
- [X] I've given this issue the correct labels

### Environment details

- [X] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version: 4ad6e0e

Operating System and version: Windows 10 Pro version 10.0.19041 Build 19041

Python version: 3.7.10 

Path to Python binary: /home/kb/anaconda3/envs/shim_venv/bin/python 

### Bug Description

When I try to use st_prepare_fieldmap with my simulated data from Zubal phantom, I end up with `RuntimeError : read_nii must range from -pi to pi` though I made my fieldmap range between -pi to pi. 

### Reproduction Steps

As the Zubal phantom is private and can't be shared, I will share the data that have been nullified.

[time_serie_inspiration_fieldmap_data.zip](https://github.com/shimming-toolbox/shimming-toolbox/files/6863599/time_serie_inspiration_fieldmap_data.zip)

As seen in the screenshot, just run st_prepare_fieldmap with these data with the options `--unwrapper "prelude"` and `--gaussian-filter False`

### Potential Reasons behind Bug:

I think it may be missing info in the JSON file since it's a JSON file that I've made for st_realtime_shim without thinking of the requierement of st_prepare_fieldmap.

### Screenshots:

![image](https://user-images.githubusercontent.com/83981856/126664101-d3a7d8bd-d06e-4ed1-b4ff-6c67256217e4.png)

**Comment by po09i** [comment] 2021-07-23 15:24
I can't reproduce your error. I think making all the values to 0 is the reason it now works.

Comments: 
- `st_prepare_fieldmap` will rescale values to radians for you if you input a siemens acquisition. You are inputting a siemens acquisition but it is already in radians which means the function tried to rescale for you so the units are probably wrong which is why we see an error message that the values are not what is expected later in the execution. We should update the doc and the function to be clearer. The proper units to enter should range from 0 to 4095 where 0 --> 0pi and 4095 --> 2pi.

- I see you included `anat` in your dataset, I usually refer to `anat` as a different acquisition to the fieldmap acquisition. Maybe this is just a difference on how we name things but the `-mag` field should be the magnitude image of the fieldmap acquisition (usually echo 1). I can't make sure since the values have been nullified but just in case.

**Comment by po09i** [comment] 2021-07-27 17:17
After a meeting with kevin, I got access to the dataset. I found out that the json file was created from scratch (used to check if rescaling should be applied). The json did not include the proper fields checked in `read_nii()` so the assumption previously made that the data was rescaled is false. We should make this obvious in `st_prepare_fieldmap()` and display a warning if there is no rescaling (1). We should also include an option to rescale or not (2). We should make `read_nii()` and the `prepare_fieldmap()` api consistent with their range of radians (either -pi to pi or 0 to pi)(3). Update the documentation of` prepare_fieldmap()` to specify the units required (4).

@KevinBerard A temporary fix is simply to rescale the phase data from 0 to 2pi if the json file does not change. The function will remove pi. (This should be changed by implementing (1,2,3,4))

**Closed as completed** 2021-08-05 16:27 UTC
Labels: bug, help wanted, question
