### ISSUE TITLE
Code coverage not working properly when using multiprocessing

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#406] opened 2022-08-18 15:06 UTC
Now that we have fixed the CI not crashing (#329) when using multiprocessing, some other issues have emerged. Notably, the code coverage does not work properly in macOS. See #388 where lsq_optimizer does not have coverage but there are multiple tests using it and that are passing.

**Comment by po09i** [comment] 2022-08-18 15:12
If we decide to not use multiprocessing in the CI (proposed solution in #407), this would also fix this issue.

**Comment by joshuacwnewton** [comment] 2022-08-18 18:03
> Notably, the code coverage does not work properly in macOS. See #388 where lsq_optimizer does not have coverage but there are multiple tests using it and that are passing.

Just to verify, here are some coverage links for #388:

* May 18th: [Coverage Report](https://coveralls.io/builds/49250059), [`lsq_optimizer.py`](https://coveralls.io/builds/49250059/source?filename=shimmingtoolbox%2Foptimizer%2Flsq_optimizer.py)
    * All of the covered lines say "6x", meaning they were hit across all 6 of the OSs. (4x Ubuntu, 2x macOS)
* June 30th: [Coverage Report](https://coveralls.io/builds/50495375), [`lsq_optimizer.py`](https://coveralls.io/builds/50495375/source?filename=shimmingtoolbox%2Foptimizer%2Flsq_optimizer.py) 
    * Many of the covered lines show "5x", and there are even some "4x", "2x", and "1x" lines, meaning that some of the OSs aren't reporting coverage.

If we look at the June 30th CI runs, we can get the URLs for the 2 macOS-specific jobs:

1. macOS-10.15, 3.7: [CI run](https://github.com/shimming-toolbox/shimming-toolbox/runs/7133688960?check_suite_focus=true#step:18:33), [Coverage Report](https://coveralls.io/jobs/102254720), [`lsq_optimizer.py`](https://coveralls.io/jobs/102254720/source_files/22815948250): 30.00%
2. macOS 10-15, 3.8: [CI Run](https://github.com/shimming-toolbox/shimming-toolbox/runs/7133689084?check_suite_focus=true#step:18:39), [Coverage Report](https://coveralls.io/jobs/102254899), [`lsq_optimizer.py`](https://coveralls.io/jobs/102254899/source_files/22816064982): 89.31%

So, there is definitely a discrepancy in CI runs for #388 -- macOS seems like it's started underreporting, as you say.

**Comment by joshuacwnewton** [comment] 2022-08-18 18:13
Now, to double-check if `multiprocessing` is the cause. 

If we focus on commit https://github.com/shimming-toolbox/shimming-toolbox/pull/388/commits/710e30a4dc0096be363a292e4f77a3e394709984, which is where #390 was merged into #388, we see:

1. macOS-10.15, 3.7: [CI run](https://github.com/shimming-toolbox/shimming-toolbox/runs/6749062273?check_suite_focus=true#step:18:33), [Coverage Report](https://coveralls.io/jobs/100669904), [`lsq_optimizer.py`](https://coveralls.io/jobs/100669904/source_files/21721853623): 90.52%

So, it looks like coverage % was still high even when `multiprocessing` was added. Maybe there's a different cause?

**Comment by joshuacwnewton** [comment] 2022-08-18 18:13
Looking at additional commits from #388, I think the big drop in coverage for `lsq_optimizer.py` actually happened in commit https://github.com/shimming-toolbox/shimming-toolbox/pull/388/commits/bfad338ba97044bfcaae233efae1ce90009a8295. You can see in the [Coverage Report](https://coveralls.io/jobs/100671054) that the # of lines covered fell dramatically:

![image](https://user-images.githubusercontent.com/16181459/185465109-7698d1e8-f7a9-4c76-b578-5c2ed52efc47.png)

So, I think this might be unrelated to `multiprocessing`? 

Still, I don't quite understand how the changes from commit https://github.com/shimming-toolbox/shimming-toolbox/pull/388/commits/bfad338ba97044bfcaae233efae1ce90009a8295 would cause such a big drop. :thinking:

**Comment by po09i** [comment] 2022-08-31 23:01
> Still, I don't quite understand how the changes from commit https://github.com/shimming-toolbox/shimming-toolbox/commit/bfad338ba97044bfcaae233efae1ce90009a8295 would cause such a big drop.

I agree that the coverage reports are odd (nothing from this commit would make the coverage decrease like this).

However, looking at where the coverage decreases is an effect of multiprocessing (this gets called by multiprocessing code [here](https://coveralls.io/jobs/100671054/source_files/21722188737#L877)): [Lines](https://coveralls.io/jobs/100671054/source_files/21722188737#L900 ) that should see cover but don't.

**Comment by po09i** [comment] 2022-09-01 20:38
Reading the [coverage](https://coverage.readthedocs.io/en/latest/index.html?highlight=pytest#quick-start) and [pytest-cov](https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html#if-you-use-multiprocessing-pool) documentation both suggest that steps need to be taken to support multiprocessing.

In our case, we use pytest-cov (implementation of coverage in pytest) where they require multiprocessing pools to exit using `pool.join` instead of relying on the context manager (see the linked doc). I implemented the fix in [344e765](https://github.com/shimming-toolbox/shimming-toolbox/pull/388/commits/344e76546d1c612fbb3c88e7672e683befdd613c) and it seems to have fixed the problem (i.e., the coverage now makes sense)

![Screen Shot 2022-09-01 at 4 37 51 PM](https://user-images.githubusercontent.com/47249340/188007786-e1bb4adb-c1d3-4776-acfb-45e6c57e9a1f.png)

**Closed as completed** 2022-10-03 22:48 UTC
Labels: bug
