### ISSUE TITLE
Versioning strategy for Shimming Toolbox

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#528] opened 2024-06-25 18:51 UTC
### Context
Shimming Toolbox is set up between 2 repos
- [Shimming Toolbox](https://github.com/shimming-toolbox/shimming-toolbox)
- [FSLeyes plugin](https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox)

Currently, a user downloads the main branch of the plugin and runs the plugin installer. The installer downloads and installs a [specific commit](https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/blob/c58065807653a5e98cacc756d7fc041815fb7875/installer/install_shimming_toolbox.sh#L17) of Shimming Toolbox.

We want to be able to version Shimming Toolbox. It would also make sense to have a version of the plugin as well.

**Comment by po09i** [comment] 2024-06-25 20:03
Here is an idea:
- Create releases for ST (x.y.z)
- Create releases for the plugin (x.y.z)

This might create some confusion though but I think it makes sense if we have 2 repos that we should have versions tracking both the plugin and ST.

ST documentation always links to latest FSLeyes release
I found this [One Liner to Download the Latest Release from Github Repo](https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8) that we could try out. Otherwise, we can link to the [release page](https://github.com/shimming-toolbox/shimming-toolbox/releases) and make the user download it.

Con:
- The release the user would download would not match the ST release.. That might be confusing.. We would add it in the release note of the plugin...

Note: I first thought it would be neat to have some similarities between the numbering scheme version of ST and the plugin so that we could know at a glance which features of ST are in the plugin (e.g. ST: 3.4.x, plugin 3.4.y). However, there are updates to the plugin that don't include adding the features of ST and they would not fit well within that numbering scheme.

**Comment by po09i** [comment] 2024-06-25 20:06
We could merge the plugin in ST

Pro
- Single simple version

Con:
- Quite a bit of work
- We need to download FSLeyes when pip installing ST

**Comment by mathieuboudreau** [comment] 2024-06-25 23:14
This feels somewhat similar to what we encountered in AxonDeepSeg with our initial FSLeyes plugin - though our workflow was not the same. Tagging @Stoyan-I-A since this maybe is something that he thought about.

**Comment by mathieuboudreau** [comment] 2024-06-26 15:51
Another thing I recalled: for ADS, we would manually "add/install" the plugin in the FSLeyes interface after opening it for the first time. One issue we encountered, was that FSLeyes would copy our plugin file to a `.fsleyes` folder in the user's home directory, and when we would update AxonDeepSeg (either via pull or clone), the plugin would become "out-of-sinc" with the new one we would pull (if there was an update). This is why we chose to keep a version specific to our plugin file;  often there was a lot of updates to ADS, but the plugin interface was not changed, and keeping a version just for the plugin helped us keep track of this file / view and compare the file currently installed on a system vs the one pulled.

However, though helpful for developers, this would also lead to some confusion as there was no "relationship" between the version of a plugin file and the base software version (we would thus ask users to always reinstall the plugin when updating ADS).

**Comment by mathieuboudreau** [comment] 2024-06-26 15:52
Also note that we kept the plugin in the same repo as the base software, but I think maybe our plugin was more rudimentary than ST's

**Comment by mathieuboudreau** [comment] 2024-06-26 16:27
>We need to download FSLeyes when pip installing ST

For ADS, we had to move away from using PIP releases because of this (not ideal I know), and instead have a self-contained conda installation that installed both FSLeyes and our software. We didn't have any complaints about this move though from our users

**Comment by po09i** [comment] 2024-06-27 14:41
During a meeting, we settled on merging the 2 repos
- 2 packages in the same repo
- High level src folder
  - Sub-folder for ST
    - Tests
    - setup.py
  - Sub folder for the plugin
    - Tests
    - setup.py

First step: Test to make sure it works and that there is nothing preventing this from happening

**Comment by po09i** [comment] 2024-07-31 15:31
The next step is to move to version 1.0 and create a ChangeLog page in the documentation. I'm thinking of one changelog page per package (ST and the plugin). Version 1.0 would describe the current features than the changelog would track the PRs for each version. A python [script](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/1152/files) in SCT could help with that.

**Comment by po09i** [comment] 2024-07-31 20:56
I'm seeing that a "[changelog](https://github.com/neuropoly/changelog)" repo has been created in the neuropoly org. We should probably use that.

**Comment by po09i** [comment] 2024-08-12 17:16
After investigating a little, the changelog repo from Neuropoly is based on milestones. I created one for version 1.0 of Shimming Toolbox and 1 for version 1.0 of the plugin. The problem is that PRs can only be assigned to a single milestone which means a PR can only be for updating either packages. This is rather inconvenient. 

A solution based around dates when PRs were closed (to differentiate between versions) combined with either labels or affected code (to differentiate between ST and plugin) might be good to look at.

**Comment by mguaypaq** [comment] 2024-08-12 19:01
I see: the ability to have PRs which touch both codebases was one of the reasons for merging the two repositories into one, so it's important.

If you want to work with two milestones (which seems reasonable), maybe it would be better to list Issues rather than PRs. Then, a single PR can close two (or more) issues, and each issue would describe the part relevant to the plugin, or to ST. I'm sure that the `changelog` script could be modified to support this.

**Comment by mguaypaq** [comment] 2024-08-12 19:49
Conclusion after voice chat:
- It's probably fine for each versioned release to contain both the plugin and the toolbox. Github automatically includes an archive of the whole repo anyway on the release page, and individual installation scripts (for either the toolbox, or the plugin, or both) can be added as assets on the same page.
- Even if some releases only touch one part or the other part, it's not a problem.
- The `changelog` script already includes the ability to group PRs under different heading by using labels (like "Documentation", "Bug fix", etc.). You could use this to group changes into "Toolbox" and/or "Plugin" very easily. (If you want 2 levels of headings, the `changelog` script could also be changed to support that later.)

**Closed as completed** 2024-08-21 20:53 UTC
Labels: feature
